import { z } from "zod";

export const planManagerProfileSchema = z.object({
  profileStep:                           z.number().int().min(0).max(20).optional(),
  // Step 2 — Role Type
  pmRoleType:                            z.enum(["PLAN_MANAGER", "PM_ORG_ADMIN", "PM_STAFF_MEMBER"]).optional(),
  // Step 1 — Business Details
  businessName:                          z.string().max(120).optional(),
  legalEntityName:                       z.string().max(120).optional(),
  abn:                                   z.string().max(20).optional(),
  acn:                                   z.string().max(20).optional(),
  businessStructure:                     z.string().max(60).optional(),
  trustName:                             z.string().max(120).optional(),
  directorName:                          z.string().max(120).optional(),
  directorPosition:                      z.string().max(80).optional(),
  businessAddress:                       z.string().max(200).optional(),
  businessSuburb:                        z.string().max(100).optional(),
  businessState:                         z.string().max(10).optional(),
  businessPostcode:                      z.string().max(10).optional(),
  businessPhone:                         z.string().max(30).optional(),
  businessEmail:                         z.string().email().optional(),
  websiteUrl:                            z.string().url().optional().or(z.literal("")),
  financeTeamEmail:                      z.string().email().optional(),
  accountsPayablePhone:                  z.string().max(30).optional(),
  yearsInOperation:                      z.string().max(20).optional(),
  // Step 3 — NDIS Registration
  ndisRegistrationStatus:                z.string().max(40).optional(),
  ndisRegistered:                        z.boolean().optional(),
  ndisProviderNumber:                    z.string().max(40).optional(),
  registrationExpiryDate:                z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date").optional(),
  approvedRegistrationGroups:            z.array(z.string()).optional(),
  // Step 4 — Capability
  planTypesSupported:                    z.array(z.string()).optional(),
  silSdaInvoicing:                       z.boolean().optional(),
  servicesProvided:                      z.array(z.string()).optional(),
  plansRecurringInvoices:                z.boolean().optional(),
  plansOnceOffInvoices:                  z.boolean().optional(),
  providesBudgetStatements:              z.boolean().optional(),
  // Step 5 — Participant Scope
  participantTypesSupported:             z.array(z.string()).optional(),
  participantComplexityExperience:       z.array(z.string()).optional(),
  // Step 6 — Service Coverage
  serviceCoverageType:                   z.string().max(40).optional(),
  stateCoverage:                         z.array(z.string()).optional(),
  serviceAreas:                          z.array(z.string()).optional(),
  postcodesServed:                       z.array(z.string()).optional(),
  timezone:                              z.string().max(60).optional(),
  operatingHours:                        z.string().max(60).optional(),
  invoiceTurnaroundTime:                 z.string().max(60).optional(),
  // Step 7 — Payment Operations
  invoiceIntakeMethod:                   z.array(z.string()).optional(),
  primaryInvoiceContactEmail:            z.string().email().optional(),
  accountsContactName:                   z.string().max(120).optional(),
  paymentEnquiryContactName:             z.string().max(120).optional(),
  paymentEnquiryContactEmail:            z.string().email().optional(),
  paymentEnquiryContactPhone:            z.string().max(30).optional(),
  invoiceReferenceFormat:                z.string().max(120).optional(),
  remittanceAdvice:                      z.string().max(200).optional(),
  disputeHandlingContact:                z.string().max(200).optional(),
  staffFinanceTeamEmail:                 z.string().email().optional(),
  acceptsRegisteredProvidersOnly:        z.boolean().optional(),
  requiresServiceDatesOnInvoices:        z.boolean().optional(),
  requiresSupportCategoryCode:           z.boolean().optional(),
  // Step 8 — Compliance
  recordKeepingDeclaration:              z.boolean().optional(),
  conflictOfInterestDeclaration:         z.boolean().optional(),
  noMisuseOfFundsDeclaration:            z.boolean().optional(),
  taxComplianceDeclaration:              z.boolean().optional(),
  informationAccurateDeclaration:        z.boolean().optional(),
  complaintsContactName:                 z.string().max(120).optional(),
  complaintsContactEmail:                z.string().email().optional(),
  incidentEscalationContact:             z.string().max(200).optional(),
  privacyContact:                        z.string().max(200).optional(),
  recordsRetentionContact:               z.string().max(200).optional(),
  // Step 9 — Staff Model
  organisationUserModel:                 z.string().max(40).optional(),
  staffAdminName:                        z.string().max(120).optional(),
  staffAdminEmail:                       z.string().email().optional(),
  staffSeatsRequired:                    z.number().int().min(0).max(9999).optional(),
  // Step 10 — Participant Linking
  participantLinkingMethod:              z.array(z.string()).optional(),
  linkApprovalRequired:                  z.boolean().optional(),
  requiresServiceAgreementBeforeInvoicing: z.boolean().optional(),
  // Step 11 — Provider Interaction
  invoiceAcceptanceRules:                z.array(z.string()).optional(),
  acceptsRecurringClaims:                z.boolean().optional(),
  acceptsOnceOffClaims:                  z.boolean().optional(),
  allowsProviderPortalMessaging:         z.boolean().optional(),
  // Step 13 — Communication
  invoiceNotificationEmail:              z.string().email().optional(),
  complianceNoticesEmail:                z.string().email().optional(),
  escalationContactForFailedPayments:    z.string().max(200).optional(),
  smsAlertsEnabled:                      z.boolean().optional(),
  // Step 14 — Commercial
  subscriptionPlan:                      z.string().max(40).optional(),
  billingContactName:                    z.string().max(120).optional(),
  billingContactEmail:                   z.string().email().optional(),
  billingAddress:                        z.string().max(200).optional(),
  gstRegistered:                         z.boolean().optional(),
  // Step 15 — Terms
  acceptingClients:                      z.boolean().optional(),
  privacyPolicyAccepted:                 z.boolean().optional(),
  confirmAuthorityToRegister:            z.boolean().optional(),
  confirmDetailsAccurate:                z.boolean().optional(),
  consentToVerification:                 z.boolean().optional(),
  consentToParticipantLinkingControls:   z.boolean().optional(),
  consentToInvoiceRoutingRules:          z.boolean().optional(),
  termsAccepted:                         z.boolean().optional(),
  ndisCodeAccepted:                      z.boolean().optional(),
});

export type PlanManagerProfileInput = z.infer<typeof planManagerProfileSchema>;
