-- Migration: add_registration_fields
-- Adds all missing fields across ParticipantProfile, WorkerProfile,
-- ProviderProfile, CoordinatorProfile, and PlanManagerProfile.

-- ─── ParticipantProfile ──────────────────────────────────────────────────────
ALTER TABLE "ParticipantProfile"
  ADD COLUMN IF NOT EXISTS "participantType"            TEXT,
  ADD COLUMN IF NOT EXISTS "suburb"                     TEXT,
  ADD COLUMN IF NOT EXISTS "postcode"                   TEXT,
  ADD COLUMN IF NOT EXISTS "state"                      TEXT,
  ADD COLUMN IF NOT EXISTS "supportCoordinationFunding" TEXT,
  ADD COLUMN IF NOT EXISTS "ndisStartDate"              TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "ndisEndDate"                TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "primarySupportNeeds"        JSONB,
  ADD COLUMN IF NOT EXISTS "preferredSupportType"       TEXT,
  ADD COLUMN IF NOT EXISTS "preferredWorkerGender"      TEXT,
  ADD COLUMN IF NOT EXISTS "languagePreference"         TEXT,
  ADD COLUMN IF NOT EXISTS "culturalPreference"         TEXT,
  ADD COLUMN IF NOT EXISTS "skillsRequired"             JSONB,
  ADD COLUMN IF NOT EXISTS "preferredDays"              JSONB,
  ADD COLUMN IF NOT EXISTS "preferredTime"              TEXT,
  ADD COLUMN IF NOT EXISTS "privacyPolicyAccepted"      BOOLEAN NOT NULL DEFAULT false;

-- ─── WorkerProfile ────────────────────────────────────────────────────────────
ALTER TABLE "WorkerProfile"
  ADD COLUMN IF NOT EXISTS "postcode"                   TEXT,
  ADD COLUMN IF NOT EXISTS "suburb"                     TEXT,
  ADD COLUMN IF NOT EXISTS "state"                      TEXT,
  ADD COLUMN IF NOT EXISTS "canTransportParticipants"   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "sleeperAvailability"        BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "hourlyRateType"             TEXT,
  ADD COLUMN IF NOT EXISTS "weekendNightRates"          JSONB,
  ADD COLUMN IF NOT EXISTS "travelCharges"              TEXT,
  ADD COLUMN IF NOT EXISTS "preferredParticipantType"   JSONB,
  ADD COLUMN IF NOT EXISTS "genderPreference"           TEXT,
  ADD COLUMN IF NOT EXISTS "languagesSpoken"            JSONB,
  ADD COLUMN IF NOT EXISTS "manualHandlingCompleted"    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "firstAidCertType"           TEXT,
  ADD COLUMN IF NOT EXISTS "termsAccepted"              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "ndisCodeAccepted"           BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "privacyPolicyAccepted"      BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "declarationStatement"       BOOLEAN NOT NULL DEFAULT false;

-- ─── ProviderProfile ─────────────────────────────────────────────────────────
ALTER TABLE "ProviderProfile"
  ADD COLUMN IF NOT EXISTS "ndisAuditStatus"                    TEXT,
  ADD COLUMN IF NOT EXISTS "secondaryContactName"               TEXT,
  ADD COLUMN IF NOT EXISTS "secondaryContactRole"               TEXT,
  ADD COLUMN IF NOT EXISTS "secondaryContactPhone"              TEXT,
  ADD COLUMN IF NOT EXISTS "secondaryContactEmail"              TEXT,
  ADD COLUMN IF NOT EXISTS "publicLiabilityPolicyNumber"        TEXT,
  ADD COLUMN IF NOT EXISTS "publicLiabilityCoverageAmount"      TEXT,
  ADD COLUMN IF NOT EXISTS "professionalIndemnityPolicyNumber"  TEXT,
  ADD COLUMN IF NOT EXISTS "workersCompPolicyNumber"            TEXT,
  ADD COLUMN IF NOT EXISTS "complianceDeclaration"              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "silType"                            TEXT,
  ADD COLUMN IF NOT EXISTS "silSupportLevel"                    TEXT,
  ADD COLUMN IF NOT EXISTS "silCurrentVacancies"                BOOLEAN,
  ADD COLUMN IF NOT EXISTS "sdaDesignCategory"                  JSONB,
  ADD COLUMN IF NOT EXISTS "sdaVacancyCount"                    INTEGER,
  ADD COLUMN IF NOT EXISTS "sdaLocations"                       JSONB,
  ADD COLUMN IF NOT EXISTS "multipleLocations"                  JSONB,
  ADD COLUMN IF NOT EXISTS "staffCapability"                    JSONB,
  ADD COLUMN IF NOT EXISTS "abilityToFillUrgentShifts"          BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "workforceHiringType"                TEXT,
  ADD COLUMN IF NOT EXISTS "currentCapacityStatus"              TEXT,
  ADD COLUMN IF NOT EXISTS "abilityToPostLiveAvailability"      BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "participantComplexityAccepted"      JSONB,
  ADD COLUMN IF NOT EXISTS "travelCharges"                      TEXT,
  ADD COLUMN IF NOT EXISTS "cancellationPolicy"                 TEXT,
  ADD COLUMN IF NOT EXISTS "canPostRequests"                    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "canViewWorkerMarketplace"           BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "canPostWorkerRequirements"          BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "canPostSilSdaVacancies"             BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "socialLinks"                        JSONB,
  ADD COLUMN IF NOT EXISTS "termsAccepted"                      BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "ndisCodeAccepted"                   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "privacyPolicyAccepted"              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "serviceAgreementAccepted"           BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "platformRulesAccepted"              BOOLEAN NOT NULL DEFAULT false;

-- ─── CoordinatorProfile ──────────────────────────────────────────────────────
ALTER TABLE "CoordinatorProfile"
  ADD COLUMN IF NOT EXISTS "gender"                TEXT,
  ADD COLUMN IF NOT EXISTS "qualifications"        JSONB,
  ADD COLUMN IF NOT EXISTS "serviceRadius"         INTEGER,
  ADD COLUMN IF NOT EXISTS "availabilityType"      TEXT,
  ADD COLUMN IF NOT EXISTS "travelCharges"         TEXT,
  ADD COLUMN IF NOT EXISTS "consentForVerification" BOOLEAN NOT NULL DEFAULT false;

-- ─── PlanManagerProfile ──────────────────────────────────────────────────────
ALTER TABLE "PlanManagerProfile"
  ADD COLUMN IF NOT EXISTS "legalEntityName"                         TEXT,
  ADD COLUMN IF NOT EXISTS "businessStructure"                       TEXT,
  ADD COLUMN IF NOT EXISTS "businessAddress"                         TEXT,
  ADD COLUMN IF NOT EXISTS "businessSuburb"                         TEXT,
  ADD COLUMN IF NOT EXISTS "businessPostcode"                        TEXT,
  ADD COLUMN IF NOT EXISTS "businessState"                           TEXT,
  ADD COLUMN IF NOT EXISTS "businessPhone"                           TEXT,
  ADD COLUMN IF NOT EXISTS "businessEmail"                           TEXT,
  ADD COLUMN IF NOT EXISTS "websiteUrl"                              TEXT,
  ADD COLUMN IF NOT EXISTS "acn"                                     TEXT,
  ADD COLUMN IF NOT EXISTS "trustName"                               TEXT,
  ADD COLUMN IF NOT EXISTS "directorName"                            TEXT,
  ADD COLUMN IF NOT EXISTS "directorPosition"                        TEXT,
  ADD COLUMN IF NOT EXISTS "financeTeamEmail"                        TEXT,
  ADD COLUMN IF NOT EXISTS "accountsPayablePhone"                    TEXT,
  ADD COLUMN IF NOT EXISTS "yearsInOperation"                        TEXT,
  ADD COLUMN IF NOT EXISTS "ndisRegistrationStatus"                  TEXT,
  ADD COLUMN IF NOT EXISTS "ndisProviderNumber"                      TEXT,
  ADD COLUMN IF NOT EXISTS "registrationExpiryDate"                  TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "approvedRegistrationGroups"              JSONB,
  ADD COLUMN IF NOT EXISTS "servicesProvided"                        JSONB,
  ADD COLUMN IF NOT EXISTS "plansRecurringInvoices"                  BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "plansOnceOffInvoices"                    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "providesBudgetStatements"                BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "participantTypesSupported"               JSONB,
  ADD COLUMN IF NOT EXISTS "participantComplexityExperience"         JSONB,
  ADD COLUMN IF NOT EXISTS "serviceCoverageType"                     TEXT,
  ADD COLUMN IF NOT EXISTS "stateCoverage"                           JSONB,
  ADD COLUMN IF NOT EXISTS "postcodesServed"                         JSONB,
  ADD COLUMN IF NOT EXISTS "timezone"                                TEXT,
  ADD COLUMN IF NOT EXISTS "operatingHours"                          TEXT,
  ADD COLUMN IF NOT EXISTS "invoiceTurnaroundTime"                   TEXT,
  ADD COLUMN IF NOT EXISTS "invoiceIntakeMethod"                     JSONB,
  ADD COLUMN IF NOT EXISTS "primaryInvoiceContactEmail"              TEXT,
  ADD COLUMN IF NOT EXISTS "accountsContactName"                     TEXT,
  ADD COLUMN IF NOT EXISTS "paymentEnquiryContactName"              TEXT,
  ADD COLUMN IF NOT EXISTS "paymentEnquiryContactEmail"              TEXT,
  ADD COLUMN IF NOT EXISTS "paymentEnquiryContactPhone"              TEXT,
  ADD COLUMN IF NOT EXISTS "invoiceReferenceFormat"                   TEXT,
  ADD COLUMN IF NOT EXISTS "acceptsRegisteredProvidersOnly"          BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "requiresServiceDatesOnInvoices"          BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "requiresSupportCategoryCode"             BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "recordKeepingDeclaration"                BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "conflictOfInterestDeclaration"           BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "noMisuseOfFundsDeclaration"              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "taxComplianceDeclaration"                BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "informationAccurateDeclaration"          BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "complaintsContactName"                   TEXT,
  ADD COLUMN IF NOT EXISTS "complaintsContactEmail"                  TEXT,
  ADD COLUMN IF NOT EXISTS "incidentEscalationContact"               TEXT,
  ADD COLUMN IF NOT EXISTS "privacyContact"                          TEXT,
  ADD COLUMN IF NOT EXISTS "recordsRetentionContact"                 TEXT,
  ADD COLUMN IF NOT EXISTS "organisationUserModel"                   TEXT,
  ADD COLUMN IF NOT EXISTS "staffAdminName"                          TEXT,
  ADD COLUMN IF NOT EXISTS "staffAdminEmail"                         TEXT,
  ADD COLUMN IF NOT EXISTS "staffSeatsRequired"                      INTEGER,
  ADD COLUMN IF NOT EXISTS "participantLinkingMethod"                JSONB,
  ADD COLUMN IF NOT EXISTS "linkApprovalRequired"                    BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "requiresServiceAgreementBeforeInvoicing" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "invoiceAcceptanceRules"                  JSONB,
  ADD COLUMN IF NOT EXISTS "acceptsRecurringClaims"                  BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "acceptsOnceOffClaims"                    BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowsProviderPortalMessaging"           BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "invoiceNotificationEmail"                TEXT,
  ADD COLUMN IF NOT EXISTS "complianceNoticesEmail"                  TEXT,
  ADD COLUMN IF NOT EXISTS "smsAlertsEnabled"                        BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "escalationContactForFailedPayments"      TEXT,
  ADD COLUMN IF NOT EXISTS "subscriptionPlan"                        TEXT,
  ADD COLUMN IF NOT EXISTS "billingContactName"                      TEXT,
  ADD COLUMN IF NOT EXISTS "billingContactEmail"                     TEXT,
  ADD COLUMN IF NOT EXISTS "billingAddress"                          TEXT,
  ADD COLUMN IF NOT EXISTS "gstRegistered"                           BOOLEAN,
  ADD COLUMN IF NOT EXISTS "privacyPolicyAccepted"                   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "confirmAuthorityToRegister"              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "confirmDetailsAccurate"                   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "consentToVerification"                   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "consentToParticipantLinkingControls"     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "consentToInvoiceRoutingRules"            BOOLEAN NOT NULL DEFAULT false;
